export type School={id:number;name:string;state:string;count:number};
export type Row=[number,number,number,number,number|null,number|null,number|null,number|null,number|null,number,number|null,'published'|'suppressed'|'unavailable'];
export type Program={id:number;school:number;field:number;credential:number;earnings:number|null;debt:number|null;estimate:number|null;low:number|null;high:number|null;support:number;size:number|null;status:Row[11]};
export function unpack(r:Row):Program{return {id:r[0],school:r[1],field:r[2],credential:r[3],earnings:r[4],debt:r[5],estimate:r[6],low:r[7],high:r[8],support:r[9],size:r[10],status:r[11]}}
export function monthlyPayment(principal:number,rate:number,years:number):number{if(!Number.isFinite(principal)||!Number.isFinite(rate)||!Number.isFinite(years)||principal<0||rate<0||years<=0)return NaN;const r=rate/1200,n=years*12;return r===0?principal/n:principal*r/(1-Math.pow(1+r,-n));}
export function position(p:Program,benchmark:number):string{if(p.earnings!==null)return p.earnings>=benchmark?'Published earnings above your benchmark':'Published earnings below your benchmark';if(p.low===null||p.high===null)return 'Not enough evidence to compare';if(p.low>benchmark)return 'Estimated range above your benchmark';if(p.high<benchmark)return 'Estimated range below your benchmark';return 'The range crosses your benchmark';}
export function normalize(s:string):string{return s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();}
export function findSchools(schools:School[],query:string):School[]{const words=normalize(query).split(' ').filter(Boolean);if(!words.length)return [];return schools.filter(s=>words.every(w=>normalize(`${s.name} ${s.state} ${s.name.split(/[^a-zA-Z]+/).filter(w=>!['of','and','the','at'].includes(w.toLowerCase())).map(w=>w[0]||'').join('')}`).includes(w))).sort((a,b)=>Number(normalize(b.name).startsWith(normalize(query)))-Number(normalize(a.name).startsWith(normalize(query)))||a.name.localeCompare(b.name)).slice(0,12);}
export function money(v:number|null):string{return v===null?'Not published':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(v);}
export function csvCell(v:unknown):string{let s=String(v??'');if(/^[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';}
export function escape(s:unknown):string{return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));}
